on:
  push:
    branches:
      - 'master'

jobs:
  sync-installers:
    if: github.repository == 'hashicorp/vagrant-builders'
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Sync Installers Repository
        run: ./.ci/sync.sh
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  sync-builders:
    if: github.repository == 'hashicorp/vagrant-installers'
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Sync Builders Repository
        run: ./.ci/sync.sh
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
